# Generated by Django 5.1.2 on 2024-10-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_student_file_remove_student_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=100)),
                ("spped", models.IntegerField(default=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
