# Generated by Django 5.1.2 on 2024-10-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0004_department_studentid_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_address",
            field=models.TextField(default=18),
        ),
    ]
