# Generated by Django 5.1.2 on 2024-10-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0006_subject_subjectmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
