# Generated by Django 5.1.2 on 2024-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0008_studentmanager_alter_student_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
